runtime: python37
instance_class: F2
inbound_services:
- warmup
automatic_scaling:
  target_cpu_utilization: 0.80
  min_idle_instances: 1
  min_instances: 1
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 30
handlers:
- url: .*
  script: auto
  secure: always
